# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.cache/wt [current_project]
set_property parent.project_path C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/RAT Assembler/prog_rom.vhd}
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/CPE233/PC.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/new/MUX.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/new/register_file.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/new/Program_counter_top.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/new/control_unit.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/imports/new/ALU.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/new/rat_cpu.vhd
  C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/sources_1/new/rat_wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/constrs_1/new/MCU_constr.xdc
set_property used_in_implementation false [get_files C:/Users/kilvl/Vivado/CPE233/MCU_top/MCU_top.srcs/constrs_1/new/MCU_constr.xdc]


synth_design -top RAT_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef RAT_wrapper.dcp

catch { report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb }
