# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.cache/wt} [current_project]
set_property parent.project_path {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.srcs/sources_1/imports/CPE233/PC.vhd}
  {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.srcs/sources_1/new/MUX.vhd}
  {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.srcs/sources_1/imports/CPE233/prog_rom.vhd}
  {C:/Users/kilvl/Vivado/CPE233/Expirement 3 Program Counter/Expirement 3 Program Counter.srcs/sources_1/new/Program_counter_top.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Program_counter_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Program_counter_top.dcp

catch { report_utilization -file Program_counter_top_utilization_synth.rpt -pb Program_counter_top_utilization_synth.pb }
